### PR TITLE
feat: drop `spicetify-` from name & move to `main`

### PR DESCRIPTION
**Pull request by afonsojramos**

### CODE REVIEW

**Review by rxri — APPROVED** [review]
Seems fine but test is needed if everything builds

**Comment by rxri** [comment]
But wrapper needs a change as well iirc

**Comment by afonsojramos** [comment]
> why renaming it to cli if its going to be a tui 😨

we're not renaming, we're just removing the `spicetify-` from the name

**Review by Delusoire — APPROVED** [review]
Looks all good👍

**Review by rxri — APPROVED** [review]

**Pull request merged**
